package day45_Interface01;

public interface Interface01 {

	public void motor(); // interface icinde abstract methodlar ve ozel concrete methodlar olabilir
	
	// Abstract methodun body si yoktur. dinamik ozelligi nasil gerceklestirecek bilemeyiz...
	// Sadece ne yapacagini biliriz...
	
	// Bu method sunu der ; Beni inherit eden her concrete class in dinamik motor ozelligi olmalidir...

	
	
	// Interface de sadece public methodlar ve abstract olur...
	// Java yazsak t yazmasakta tum methodlari bu sekilde kabul eder...
	// Tum methodlar public ve abstract tir...
	
	public abstract void sanzuman();
	void vites(); // Bunun basinda public abstract vardir...
	abstract void kasa(); // Bunun basinda da public vardir...
	
	
	// Java da interface olusturmak istiyorsak o sekilde olusturmaliyiz.
	// Bir class sonradan interface yapilamaz. Class degil direk interface olarak olusturulur...
	
	
	String ISIM="Mustafa";
	// Java isim kelimesini static ve bold yapti.
	// Demek ki tum variable lar final ve static tir...
	// isim buyuk yazilmalidir...
	 
	// VARIABLE LAR ABSTRACT OLMAZ...
	
	
}
